### ISSUE TITLE
Issue from ÉTS Mobile 

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#284] opened 2021-11-01 15:10 UTC
**Describe the issue** 
```no longer receive notifications for new grades```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-334483467.png?raw=true)

**Device Infos** 
- **Device:** SM-G950W 
- **Version:** 4.4.8 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1634853217 
- **Platform operating system:** android 
- **Platform operating system version:** PPR1.180610.011.G950WVLU8CUF3

**Comment by camillebrulotte** [comment] 2021-11-01 15:13
Duplicate of #29

**Closed by camillebrulotte** 2021-11-01 15:13 UTC
Labels: bug, platform: android
