### ISSUE TITLE
Grade can't open when clicked on it (FIXED in 4.2.3)

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#208] opened 2021-09-22 01:51 UTC
**Describe the issue** 
```on n’arrive pas à ouvrir les notes comme avant. ```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-1070848272.png?raw=true)

**Device Infos** 
- **Version:** 4.2.2 
- **Connectivity:** ConnectivityResult.mobile 
- **Build number:** 1631833857 
- **Platform operating system:** ios 
- **Platform operating system version:** 14.7.1

**Comment by MysticFragilist** [comment] 2021-09-22 02:19
I'm not sure but I think it's fix in 4.2.3 right? What's the current version of the app?

**Comment by apomalyn** [comment] 2021-09-22 03:21
@MysticFragilist it's fixed in 4.2.3 exact 😄 sorry for the wait but the PR is landing soon (I hope tomorrow...)

**Comment by apomalyn** [comment] 2021-09-22 03:21
Duplicate of #186

**Closed by apomalyn** 2021-09-22 03:21 UTC
Labels: bug, duplicate, platform: ios

**Comment by MysticFragilist** [comment] 2021-09-22 05:06
Perfect 😄 and no problem @apomalyn! I'll review it when it arrives
