### ISSUE TITLE
Issue from  

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame#190] opened 2021-09-18 17:10 UTC
**Describe the issue** 
```Je n’arrive pas à accéder aux notes de mes cours antérieurs```

**Screenshot** 
![screenshot](https://github.com/ApplETS/Notre-Dame-Bug-report/blob/main/bugPicture-516288095.png?raw=true)

**Device Infos** 
- **Version:** 4.2.2 
- **Connectivity:** ConnectivityResult.wifi 
- **Build number:** 1631833857 
- **Platform operating system:** ios 
- **Platform operating system version:** 14.7.1

**Comment by apomalyn** [comment] 2021-09-19 21:33
Duplicate of #188

**Closed** 2021-09-19 21:34 UTC
Labels: bug, duplicate, platform: ios
